ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.mashiverse.HttpKt.configureHttp
      - com.mashiverse.SerializationKt.configureSerialization
      - com.mashiverse.PostgresKt.configurePostgres
      - com.mashiverse.RoutingKt.configureRouting
