ktor:
  deployment:
    port: 3000
  application:
    modules:
      - com.mashiverse.HttpKt.configureHttp
      - com.mashiverse.SerializationKt.configureSerialization
      - com.mashiverse.PostgresKt.configurePostgres
      - com.mashiverse.server.routes.MashupRoutesKt.mashupRoutes
      - com.mashiverse.data.di.KoinKt.configureKoin
