ktor:
  deployment:
    port: 3000
  application:
    modules:
      - com.mashiverse.utils.other.HttpKt.configureHttp
      - com.mashiverse.utils.other.SerializationKt.configureSerialization
      - com.mashiverse.server.routes.MashupRoutesKt.mashupRoutes
      - com.mashiverse.data.di.KoinKt.configureKoin
      - com.mashiverse.server.routes.CorrectionRoutesKt.correctionRoutes
      - com.mashiverse.server.routes.NotifyRoutesKt.notifyRoutes
